### ISSUE TITLE
No SSL on blinderkitten.lighting

### ISSUE THREAD

**Issue by gavmor** [norbertrostaing/BlinderKitten#2]
Please update / install certificates on your main website, as I am uncomfortable recommending downloads from a site without SSL. Additionally, please consider releasing binaries via GitHub, as well.

**Comment by norbertrostaing** [comment]
I've added ssls to my todo task. 
I will try to automatise gihub releases
Thanks for your feedback :)

**Comment by moemoeq** [comment]
First of all, thank you for the wonderful project.
there is quick and easy solution. how about using cloudflare?
it's simple, just change dns to cloudflare next, setup records and enable https on their console. 
(I am not affiliated with cloudflare.)

**Comment by amreo** [comment]
SSL is still broken...

**Comment by norbertrostaing** [comment]
I know, I must figure a solution to install it on my server, or change my provider

**Comment by niklasberlin** [comment]
Any news on ssl for the website?

Most hosters offer free ssl certificates from lets encrypt that can be easily activated in the control panel. Most hosters usually provide also some documentation on how to enable that on their system. For example this is the corresponding help article from OVH (one of the bigger cloud providers in europe):
https://help.ovhcloud.com/csm/en-ie-web-hosting-ssl-certificates?id=kb_article_view&sysparm_article=KB0053180

In addition to that you might want to add a .htaccess file to your root directory of your webserver so that all traffic is redirected to use the secure ssl connection. An instruction on how to do this on OVH Servers can be found here:
https://help.ovhcloud.com/csm/en-ie-web-hosting-htaccess-url-rewriting?id=kb_article_view&sysparm_article=KB0052870#automatically-redirect-a-visitor-to-use-https-when-the-website-was-accessed-using-a-http-url

feel free to reach out if you need additional help

**Comment by norbertrostaing** [comment]
Hi there
It is still work in progress, I actually need to change my server, the data
center will close at the end of the year.
I will probably rent a new server in july and migrate to a new version of
my OS, the current OS is very old and not maintained :'(
Thanks a lot for your request, I think it's gonna the next work on my list,
this needs a massive clean I agree

Le mar. 18 juin 2024 à 22:58, niklasberlin ***@***.***> a
écrit :

**Comment by norbertrostaing** [comment]
Hi there, SSL should be activated on blinderkitten.lighting
Can you confirm everything's ok ?
Thanks

**Comment by amreo** [comment]
It seems OK to me. I think that this issue can be closed.

**Comment by norbertrostaing** [comment]
server migration OK  :)
